version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_gestion_activites
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: GestionActivites
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mariadb_data_m1_s1_model:/var/lib/mysql

volumes:
  mariadb_data_m1_s1_model:
